apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: airshipmachineproviderspecs.airshipprovider.kubekit.cloud
spec:
  group: airshipprovider.kubekit.cloud
  names:
    kind: AirshipMachineProviderSpec
    plural: airshipmachineproviderspecs
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        baremetalspec:
          properties:
            addressing:
              items:
                properties:
                  address:
                    type: string
                  network:
                    type: string
                type: object
              type: array
            interfaces:
              type: object
            metadata:
              properties:
                rack:
                  type: string
                tags:
                  items:
                    type: string
                  type: array
              type: object
            oob:
              properties:
                account:
                  type: string
                credetial:
                  type: string
                network:
                  type: string
                type:
                  type: string
              type: object
            platform:
              properties:
                image:
                  type: string
                kernel:
                  type: string
              type: object
            storage:
              type: object
          type: object
        kind:
          type: string
        metadata:
          type: object
        roles:
          items:
            type: string
          type: array
      required:
      - baremetalspec
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
