apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: airshipclusterproviderspecs.airshipprovider.kubekit.cloud
spec:
  group: airshipprovider.kubekit.cloud
  names:
    kind: AirshipClusterProviderSpec
    plural: airshipclusterproviderspecs
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        caCertificate:
          format: byte
          type: string
        caKey:
          format: byte
          type: string
        kind:
          type: string
        location:
          type: string
        metadata:
          type: object
        resourceGroup:
          type: string
      required:
      - resourceGroup
      - location
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
