// Code generated by schema-generate. DO NOT EDIT.

package armada

// Root
type ArmadaChartGroupSchema struct {
	ChartGroup  []string `json:"chart_group"`
	Description string   `json:"description,omitempty"`
	Name        string   `json:"name,omitempty"`
	Sequenced   bool     `json:"sequenced,omitempty"`
	TestCharts  bool     `json:"test_charts,omitempty"`
}
