// Code generated by schema-generate. DO NOT EDIT.

package armada

// Root
type ArmadaManifestSchema struct {
	ChartGroups   []string `json:"chart_groups"`
	ReleasePrefix string   `json:"release_prefix"`
}
