// Code generated by schema-generate. DO NOT EDIT.

package drydock

// DeviceAliases
type DeviceAliases struct {
	AdditionalProperties map[string]interface{} `json:"-,omitempty"`
}

// HugepagesItem
type HugepagesItem struct {
}

// Root
type HardwareProfileSpec struct {
	BiosVersion       string                    `json:"bios_version,omitempty"`
	BootMode          string                    `json:"boot_mode,omitempty"`
	BootstrapProtocol string                    `json:"bootstrap_protocol,omitempty"`
	CpuSets           map[string]string         `json:"cpu_sets,omitempty"`
	DeviceAliases     *DeviceAliases            `json:"device_aliases,omitempty"`
	Generation        string                    `json:"generation,omitempty"`
	Hugepages         map[string]*HugepagesItem `json:"hugepages,omitempty"`
	HwVersion         string                    `json:"hw_version,omitempty"`
	PxeInterface      float64                   `json:"pxe_interface,omitempty"`
	Vendor            string                    `json:"vendor,omitempty"`
}
