// Code generated by schema-generate. DO NOT EDIT.

package drydock

// DhcpRelay
type DhcpRelay struct {
	SelfIp         string `json:"self_ip,omitempty"`
	UpstreamTarget string `json:"upstream_target,omitempty"`
}

// Dns
type Dns struct {
	Domain  string `json:"domain,omitempty"`
	Servers string `json:"servers,omitempty"`
}

// Labels
type Labels struct {
	AdditionalProperties map[string]interface{} `json:"-,omitempty"`
}

// RangesItems
type RangesItems struct {
	End   string `json:"end,omitempty"`
	Start string `json:"start,omitempty"`
	Type  string `json:"type,omitempty"`
}

// Root
type NetworkSpec struct {
	Cidr        string         `json:"cidr,omitempty"`
	DhcpRelay   *DhcpRelay     `json:"dhcp_relay,omitempty"`
	Dns         *Dns           `json:"dns,omitempty"`
	Labels      *Labels        `json:"labels,omitempty"`
	Mtu         float64        `json:"mtu,omitempty"`
	Ranges      []*RangesItems `json:"ranges,omitempty"`
	Routedomain string         `json:"routedomain,omitempty"`
	Routes      []*RoutesItems `json:"routes,omitempty"`
	Vlan        string         `json:"vlan,omitempty"`
}

// RoutesItems
type RoutesItems struct {
	Gateway     string  `json:"gateway,omitempty"`
	Metric      float64 `json:"metric,omitempty"`
	Routedomain string  `json:"routedomain,omitempty"`
	Subnet      string  `json:"subnet,omitempty"`
}
