// Code generated by schema-generate. DO NOT EDIT.

package drydock

// Labels
type Labels3 struct {
	AdditionalProperties map[string]interface{} `json:"-,omitempty"`
}

// Location
type Location struct {
	Clli string `json:"clli,omitempty"`
	Grid string `json:"grid,omitempty"`
}

// Root
type RackSpec struct {
	Labels        *Labels3     `json:"labels,omitempty"`
	LocalNetworks []string     `json:"local_networks,omitempty"`
	Location      *Location    `json:"location,omitempty"`
	TorSwitches   *TorSwitches `json:"tor_switches,omitempty"`
}

// TorSwitches
type TorSwitches struct {
	MgmtIp    string `json:"mgmt_ip,omitempty"`
	SdnApiUri string `json:"sdn_api_uri,omitempty"`
}
