// Code generated by schema-generate. DO NOT EDIT.

package drydock

// Repositories
type Repositories struct {
	RemoveUnlisted bool `json:"remove_unlisted,omitempty"`
}

// Root
type RegionSpec struct {
	AuthorizedKeys []string               `json:"authorized_keys,omitempty"`
	Repositories   *Repositories          `json:"repositories,omitempty"`
	TagDefinitions []*TagDefinitionsItems `json:"tag_definitions,omitempty"`
}

// TagDefinitionsItems
type TagDefinitionsItems struct {
	Definition     string `json:"definition,omitempty"`
	DefinitionType string `json:"definition_type,omitempty"`
	Tag            string `json:"tag,omitempty"`
}
