// Code generated by schema-generate. DO NOT EDIT.

package promenade

// EncryptionMethodGpg
type EncryptionMethodGpg struct {
	Gpg *Gpg `json:"gpg"`
}

// Gpg
type Gpg struct {
}

// Root
type EncryptionPolicySpec struct {
	Scripts *Scripts `json:"scripts,omitempty"`
}

// Scripts
type Scripts struct {
	Genesis interface{} `json:"genesis,omitempty"`
	Join    interface{} `json:"join,omitempty"`
}
