// Code generated by schema-generate. DO NOT EDIT.

package promenade

// File
type File struct {
	Content string `json:"content,omitempty"`
	Mode    int    `json:"mode,omitempty"`
	Path    string `json:"path,omitempty"`
	TarPath string `json:"tar_path,omitempty"`
	TarUrl  string `json:"tar_url,omitempty"`
}

// FilesItems
type FilesItems struct {
}

// Helm
type Helm struct {
	Helm string `json:"helm"`
}

// Images
type Images struct {
	Coredns    string      `json:"coredns,omitempty"`
	Haproxy    string      `json:"haproxy"`
	Helm       *Helm       `json:"helm"`
	Kubernetes *Kubernetes `json:"kubernetes"`
}

// Kubernetes
type Kubernetes struct {
	Kubectl string `json:"kubectl"`
}

// Packages
type Packages struct {
	Additional   []string  `json:"additional,omitempty"`
	Keys         []string  `json:"keys,omitempty"`
	Repositories []string  `json:"repositories,omitempty"`
	Required     *Required `json:"required"`
}

// PodLogs
type PodLogs struct {
	Image string `json:"image,omitempty"`
}

// Required
type Required struct {
	Docker string `json:"docker"`
	Socat  string `json:"socat"`
}

// Root
type HostSystemSpec struct {
	Files        []*FilesItems           `json:"files,omitempty"`
	Images       *Images                 `json:"images"`
	Packages     *Packages               `json:"packages"`
	SystemdUnits map[string]*SystemdUnit `json:"systemd_units,omitempty"`
	Validation   *Validation             `json:"validation,omitempty"`
}

// SystemdUnit
type SystemdUnit struct {
	Disable bool `json:"disable,omitempty"`
	Enable  bool `json:"enable,omitempty"`
	Start   bool `json:"start,omitempty"`
	Stop    bool `json:"stop,omitempty"`
}

// Validation
type Validation struct {
	PodLogs *PodLogs `json:"pod_logs,omitempty"`
}
