// Code generated by schema-generate. DO NOT EDIT.

package promenade

// Labels
type Labels struct {
	Dynamic []string `json:"dynamic,omitempty"`
	Static  []string `json:"static,omitempty"`
}

// Root
type KubernetesNodeSpec struct {
	Domain   string        `json:"domain,omitempty"`
	Hostname string        `json:"hostname,omitempty"`
	Ip       string        `json:"ip"`
	JoinIp   string        `json:"join_ip,omitempty"`
	JoinIps  []interface{} `json:"join_ips,omitempty"`
	Labels   *Labels       `json:"labels,omitempty"`
}
