// Code generated by schema-generate. DO NOT EDIT.

package promenade

// Dns
type Dns struct {
	BootstrapValidationChecks []string `json:"bootstrap_validation_checks,omitempty"`
	ClusterDomain             string   `json:"cluster_domain"`
	ServiceIp                 string   `json:"service_ip"`
	UpstreamServers           []string `json:"upstream_servers,omitempty"`
}

// Etcd
type Etcd struct {
	ContainerPort int    `json:"container_port"`
	HaproxyPort   int    `json:"haproxy_port"`
	ServiceIp     string `json:"service_ip,omitempty"`
}

// HostsEntriesItems
type HostsEntriesItems struct {
	Ip    string   `json:"ip,omitempty"`
	Names []string `json:"names,omitempty"`
}

// Kubernetes
type Kubernetes2 struct {
	ApiserverPort int    `json:"apiserver_port"`
	HaproxyPort   int    `json:"haproxy_port"`
	PodCidr       string `json:"pod_cidr"`
	ServiceCidr   string `json:"service_cidr"`
	ServiceIp     string `json:"service_ip"`
}

// Proxy
type Proxy struct {
	AdditionalNoProxy []interface{} `json:"additional_no_proxy,omitempty"`
	Url               string        `json:"url"`
}

// Root
type KubernetesNetworkSpec struct {
	Dns          *Dns                 `json:"dns"`
	Etcd         *Etcd                `json:"etcd,omitempty"`
	HostsEntries []*HostsEntriesItems `json:"hosts_entries,omitempty"`
	Kubernetes   *Kubernetes2         `json:"kubernetes"`
	Proxy        *Proxy               `json:"proxy,omitempty"`
}
