// +build !ignore_autogenerated

/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by main. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AirshipClusterProviderSpec) DeepCopyInto(out *AirshipClusterProviderSpec) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AirshipClusterProviderSpec.
func (in *AirshipClusterProviderSpec) DeepCopy() *AirshipClusterProviderSpec {
	if in == nil {
		return nil
	}
	out := new(AirshipClusterProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AirshipClusterProviderSpec) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AirshipClusterProviderSpecList) DeepCopyInto(out *AirshipClusterProviderSpecList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AirshipClusterProviderSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AirshipClusterProviderSpecList.
func (in *AirshipClusterProviderSpecList) DeepCopy() *AirshipClusterProviderSpecList {
	if in == nil {
		return nil
	}
	out := new(AirshipClusterProviderSpecList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AirshipClusterProviderSpecList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AirshipClusterProviderSpecSpec) DeepCopyInto(out *AirshipClusterProviderSpecSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AirshipClusterProviderSpecSpec.
func (in *AirshipClusterProviderSpecSpec) DeepCopy() *AirshipClusterProviderSpecSpec {
	if in == nil {
		return nil
	}
	out := new(AirshipClusterProviderSpecSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AirshipClusterProviderSpecStatus) DeepCopyInto(out *AirshipClusterProviderSpecStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AirshipClusterProviderSpecStatus.
func (in *AirshipClusterProviderSpecStatus) DeepCopy() *AirshipClusterProviderSpecStatus {
	if in == nil {
		return nil
	}
	out := new(AirshipClusterProviderSpecStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AirshipClusterProviderStatus) DeepCopyInto(out *AirshipClusterProviderStatus) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AirshipClusterProviderStatus.
func (in *AirshipClusterProviderStatus) DeepCopy() *AirshipClusterProviderStatus {
	if in == nil {
		return nil
	}
	out := new(AirshipClusterProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AirshipClusterProviderStatus) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AirshipClusterProviderStatusList) DeepCopyInto(out *AirshipClusterProviderStatusList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AirshipClusterProviderStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AirshipClusterProviderStatusList.
func (in *AirshipClusterProviderStatusList) DeepCopy() *AirshipClusterProviderStatusList {
	if in == nil {
		return nil
	}
	out := new(AirshipClusterProviderStatusList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AirshipClusterProviderStatusList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AirshipClusterProviderStatusSpec) DeepCopyInto(out *AirshipClusterProviderStatusSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AirshipClusterProviderStatusSpec.
func (in *AirshipClusterProviderStatusSpec) DeepCopy() *AirshipClusterProviderStatusSpec {
	if in == nil {
		return nil
	}
	out := new(AirshipClusterProviderStatusSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AirshipClusterProviderStatusStatus) DeepCopyInto(out *AirshipClusterProviderStatusStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AirshipClusterProviderStatusStatus.
func (in *AirshipClusterProviderStatusStatus) DeepCopy() *AirshipClusterProviderStatusStatus {
	if in == nil {
		return nil
	}
	out := new(AirshipClusterProviderStatusStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AirshipMachineProviderSpec) DeepCopyInto(out *AirshipMachineProviderSpec) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AirshipMachineProviderSpec.
func (in *AirshipMachineProviderSpec) DeepCopy() *AirshipMachineProviderSpec {
	if in == nil {
		return nil
	}
	out := new(AirshipMachineProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AirshipMachineProviderSpec) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AirshipMachineProviderSpecList) DeepCopyInto(out *AirshipMachineProviderSpecList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AirshipMachineProviderSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AirshipMachineProviderSpecList.
func (in *AirshipMachineProviderSpecList) DeepCopy() *AirshipMachineProviderSpecList {
	if in == nil {
		return nil
	}
	out := new(AirshipMachineProviderSpecList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AirshipMachineProviderSpecList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AirshipMachineProviderSpecSpec) DeepCopyInto(out *AirshipMachineProviderSpecSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AirshipMachineProviderSpecSpec.
func (in *AirshipMachineProviderSpecSpec) DeepCopy() *AirshipMachineProviderSpecSpec {
	if in == nil {
		return nil
	}
	out := new(AirshipMachineProviderSpecSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AirshipMachineProviderSpecStatus) DeepCopyInto(out *AirshipMachineProviderSpecStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AirshipMachineProviderSpecStatus.
func (in *AirshipMachineProviderSpecStatus) DeepCopy() *AirshipMachineProviderSpecStatus {
	if in == nil {
		return nil
	}
	out := new(AirshipMachineProviderSpecStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AirshipMachineProviderStatus) DeepCopyInto(out *AirshipMachineProviderStatus) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AirshipMachineProviderStatus.
func (in *AirshipMachineProviderStatus) DeepCopy() *AirshipMachineProviderStatus {
	if in == nil {
		return nil
	}
	out := new(AirshipMachineProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AirshipMachineProviderStatus) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AirshipMachineProviderStatusList) DeepCopyInto(out *AirshipMachineProviderStatusList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AirshipMachineProviderStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AirshipMachineProviderStatusList.
func (in *AirshipMachineProviderStatusList) DeepCopy() *AirshipMachineProviderStatusList {
	if in == nil {
		return nil
	}
	out := new(AirshipMachineProviderStatusList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AirshipMachineProviderStatusList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AirshipMachineProviderStatusSpec) DeepCopyInto(out *AirshipMachineProviderStatusSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AirshipMachineProviderStatusSpec.
func (in *AirshipMachineProviderStatusSpec) DeepCopy() *AirshipMachineProviderStatusSpec {
	if in == nil {
		return nil
	}
	out := new(AirshipMachineProviderStatusSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AirshipMachineProviderStatusStatus) DeepCopyInto(out *AirshipMachineProviderStatusStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AirshipMachineProviderStatusStatus.
func (in *AirshipMachineProviderStatusStatus) DeepCopy() *AirshipMachineProviderStatusStatus {
	if in == nil {
		return nil
	}
	out := new(AirshipMachineProviderStatusStatus)
	in.DeepCopyInto(out)
	return out
}
